name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Restore dependencies
      run: dotnet restore ./LemonMarkets.UnitTests/LemonMarkets.UnitTests.csproj
    - name: Build
      run: dotnet build -c Release ./LemonMarkets.UnitTests/LemonMarkets.UnitTests.csproj
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal ./LemonMarkets.UnitTests/LemonMarkets.UnitTests.csproj
